### ISSUE TITLE
Homey 1.1.2 crash

### ISSUE THREAD

**Issue by elcovb** [netactivenl/com.logitech.harmony.hub#11]
Stack trace:

TypeError: Cannot read property 'client' of undefined
at Object.module.exports.sendCommandToDevice (/drivers/hub/driver.js:307:38)
at Object.<anonymous> (/app.js:74:63)
at emitThree (events.js:97:13)
at Object.emit (events.js:175:7)
at /homey-app/manager/flow.js:12:37
at /homey-app/helpers/client.js:1:1077
at Array.forEach (native)
at process.<anonymous> (/homey-app/helpers/client.js:1:1046)
at emitTwo (events.js:87:13)
at process.emit (events.js:172:7)

Exit code: 1
Exit signal: null

**Comment by netactivenl** [comment]
Have you tried v1.0.3 which is currently being tested? This issue should be revolved in that version. Code is right here in the master branch!

**Comment by fransko** [comment]
where can i find v1.0.3

**Comment by netactivenl** [comment]
Right here on GitHub in the master branch. If you're not a software developer, you'll have to wait until it's released to the app store.
