### ISSUE TITLE
several crashes 1.0.4 with homey 1.1.2

### ISSUE THREAD

**Issue by satbopper** [netactivenl/com.logitech.harmony.hub#13]
Stack trace:

Error: Uncaught, unspecified "error" event. (XMPP authentication failure)
at Client.emit (events.js:144:17)
at Client._handleAuthState (/node_modules/node-xmpp-client/lib/Client.js:298:10)
at Client._handleStanza (/node_modules/node-xmpp-client/lib/Client.js:234:12)
at Client.onStanza (/node_modules/node-xmpp-client/lib/Client.js:222:8)
at emitOne (events.js:77:13)
at Connection.emit (events.js:169:7)
at Connection.onStanza (/node_modules/node-xmpp-core/lib/Connection.js:369:10)
at StreamParser.<anonymous> (/node_modules/node-xmpp-core/lib/Connection.js:226:10)
at emitOne (events.js:77:13)
at StreamParser.emit (events.js:169:7)

Exit code: 1
Exit signal: null

**Comment by denniedegroot** [comment]
I am having the same crashes.

**Comment by Sillec123** [comment]
Me 2
